receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo_tournament:4319
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:8889'
  loki:
    endpoint: "http://loki_tournament:3100/loki/api/v1/push"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [logging, loki]
      processors: [batch]

