version: '3.8'

volumes:
  prometheus_data: {}
  grafana: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    network_mode: "host"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana/
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    user: "472" # sudo chown -R 472:472 ./grafana
    network_mode: "host"
