global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tournament-api'
    static_configs:
      - targets: ['localhost:5244']
    metrics_path: /metrics-text
